version: "3.7"
services:
  redis:
    image: "redis:alpine"
    networks:
      - proxy
      - agent_network
    deploy:
      labels:
        com.beehive.project: "${PROJECT}"
        com.beehive.environment: "${ENVIRONMENT}"
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      ENVIRONMENT: ${ENVIRONMENT}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /data/postgres
    deploy:
      labels:
        com.beehive.project: "${PROJECT}"
        com.beehive.environment: "${ENVIRONMENT}"
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - proxy
    restart: unless-stopped

networks:
  proxy:
    external: true
  agent_network:
    external: true

volumes:
    postgres: